name: deploy

on:
  push:
    tags: [ v* ]

jobs:
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Setup GCP
        uses: google-github-actions/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCS_SA_KEY }}
          project_id: ${{ secrets.GCS_PROJECT }}
          export_default_credentials: true

      - name: Build binaries
        run: |
          mkdir candi
          GOOS=linux GOARCH=amd64 go build -o candi/candi-linux cmd/candi/*.go
          GOOS=darwin GOARCH=amd64 go build -o candi/candi-osx cmd/candi/*.go
          GOOS=windows GOARCH=amd64 go build -o candi/candi-x64.exe cmd/candi/*.go
          GOOS=windows GOARCH=386 go build -o candi/candi-x86.exe cmd/candi/*.go

      - name: Deploy
        run: |-
          gsutil -m rsync -R candi gs://agungdp/bin/candi
          gsutil acl -r ch -u AllUsers:R gs://agungdp/bin/candi
